"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    name="lid", # Replace with your own username
    version="0.0.1",
    # script=["lid.py"],
    author="Christophe Prat",
    author_email="chrisotpheprat@icloud.com",
    url="https://github.com/ChristophePRAT/LinesInDirectory",
    # scripts=["lid.py"],
    python_requires='>=3.6',
    paskages=["tqdm"],
    entry_points= {
        'console_scripts': [ 
            'lid=lid:main' 
        ]   
    }
)
